### PR TITLE
feat: added extras support on pipenv-setup check, fixes #44

### LINKED ISSUE #44: pipenv-setup check fails to handle [extras]
Minimal example: hopefully enough to follow as it is an extract from a larger project.

Pipfile
```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
uvicorn = {extras = [ "standard",]}
```

pipenv-setup generates:
```
        "uvicorn[standard]==0.13.3",
```

however:
```
pipenv-setup check
package 'uvicorn' in pipfile but not in install_requires
```

expected behaviour:
check can find the translated dependency.

### PR DESCRIPTION
**Pull request by shaybensasson**

### CODE REVIEW

**Comment by den4uk** [comment]
Bump! Is this going to be merged, please?

**Comment by DanielCarmel** [comment]
Hey, we are waiting for this fix to be merged
Please do it ASAP🙏🙏🙏

**Comment by Madoshakalaka** [comment]
I'll have a look at this today

**Comment by hugochinchilla** [comment]
Can we have a new release with this merged in please?

**Pull request merged**
