### PR TITLE
Fix Tests on Windows and MacOS

### LINKED ISSUE #9: Verify travis runs tests on Windows and Mac
I fixed a bug in version 2.2.1 where a windows path should be casted to string. It's a serious bug  during file formatting, which should error a `sync` command.

This makes me wonder whether travis tests on Windows (even Mac builds) are properly configured. Here is the travis output on Windows builds, it shows no test progress, just a congratulation: 
```
$ python -m tox
___________________________________ summary ___________________________________
  congratulations :)
The command "python -m tox" exited with 0.
```
While on linux builds there are detailed test outputs

### PR DESCRIPTION
**Pull request by Madoshakalaka**
- Use python built-into specific macOS images instead of always using pyenv.

- Fixed tests on Windows and MacOS

fixes #9

### CODE REVIEW

**Comment by Madoshakalaka** [comment]
Actually maybe not deserving a new version, tests failed on old python versions on Windows. But that's resulted from tox packaging where old version of `setuptools` does not include `README.md`.

The published version does indeed include README.md

**Comment by Madoshakalaka** [comment]
@bryant-finney I moved LICENSE file from data_files keyword argument in setup.py to `MANIFEST.in`. Since `setuptools` on older python 3.5 and 3.4 on Windows does not recognize the former ( and it does not package README.md automatically either). 

details here:
[failed build caused by unpacked LICENSE ](https://travis-ci.org/Madoshakalaka/pipenv-setup/builds/612958330)

[failed build caused by unpacked README.md](https://travis-ci.org/Madoshakalaka/pipenv-setup/builds/612946189)

This failure was covered since tests were not ran on Windows and MacOS earlier as stated by #9

**Comment by bryant-finney** [comment]
So while I was messing around in python 3.5 on Windows, I noticed that [main.py:6](https://github.com/Madoshakalaka/pipenv-setup/blob/1326bf57b2d4751b9d26ab7e6949044910485a9c/pipenv_setup/main.py#L6) imports from `typing`.

How does this import work for python 2.7 *et. al*?

**Comment by Madoshakalaka** [comment]
I went investigating and I don't quite understand. Here's what the case is:

`typing` only misses on python 3.4 and python 2.7. While there's a official [backport package](https://pypi.org/project/typing/) called just "typing" 

I checked the build log for python 2.7:
[python 3.4 linux build:217](https://travis-ci.org/Madoshakalaka/pipenv-setup/jobs/612982891#L217) shows `typing==3.7.4.1` is installed

[python 2.7 linux build:217](https://travis-ci.org/Madoshakalaka/pipenv-setup/jobs/612982892#L217) also shows `typing==3.7.4.1` is installed

Windows builds show the same: `typing` packageis installed.

So that explains why `import typing` works on thoses versions...but what bothers me is I don't find `typing` in our dependencies. I tried `pipenv graph` and `typing` is missing in the dependencies. It does not exist in lockfile either. Technically `typing` shouldn't be installed. I wonder how the backport sneaks in to our dependency...

Anyways, I'll later explicity require `typing` backport in Pipfile.

**Pull request merged**
